global using System;
global using System.IO;
global using System.Linq;
global using System.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.Text;

namespace ImplicitNamespaceImportGenerator;

/// <summary>
/// Source Generator for generating the implicit global namespace imports.
/// </summary>
[Generator]
public class ImplicitNamespaceImportGenerator : ISourceGenerator
{
    /// <inheritdoc/>
    public void Initialize(GeneratorInitializationContext context)
    {
        // Source Generators do not need to fill this in.
    }

    /// <inheritdoc/>
    public void Execute(GeneratorExecutionContext context)
    {
        var importsAdditionalText = context.AdditionalFiles.FirstOrDefault(
            af => string.Equals(
                Path.GetFileName(af.Path),
                "Imports.txt",
                StringComparison.OrdinalIgnoreCase));
        if (importsAdditionalText is null)
        {
            return;
        }

        var contents = importsAdditionalText.GetText().ToString();

        // filter out duplicate namespace imports.
        var lines = contents.Split(new []{ "\r\n", "\n", "\r"}, StringSplitOptions.RemoveEmptyEntries);
        var builder = new StringBuilder();
        foreach (var line in lines.Distinct())
        {
            if ((line.StartsWith("static "), line.Contains("=")) switch
            {
                (true, false) => !((CSharpCompilation)context.Compilation).ContainsSymbolsWithName(
                    line.Substring(line.IndexOf("static ", StringComparison.Ordinal) + 7),
                    SymbolFilter.Namespace | SymbolFilter.Type),
                (false, true) => !((CSharpCompilation)context.Compilation).ContainsSymbolsWithName(
                line.Substring(line.IndexOf("=", StringComparison.Ordinal) + 2),
                SymbolFilter.Namespace | SymbolFilter.Type),
                _ => false,
            })
            {
                continue;
            }

            _ = builder.AppendLine((line.StartsWith("static "), line.Contains("=")) switch
            {
                (true, false) => $"global using {line.Insert(line.IndexOf("static ", StringComparison.Ordinal) + 7, "global::")};",
                (false, true) => $"global using {line.Insert(line.IndexOf("=", StringComparison.Ordinal) + 2, "global::")};",
                (false, false) => $"global using global::{line};",
                (true, true) => throw new InvalidOperationException("static aliases are not supported in the C# or Visual Basic Compilers."),
            });
        }

        context.AddSource(
            "GlobalUsings.g.cs",
            SourceText.From(
                $@"{(
                    string.IsNullOrEmpty(builder.ToString())
                        ? string.Empty
                        : $"// <autogenerated>{Environment.NewLine}{builder}")}",
                Encoding.UTF8));
    }
}
